package IGU;

import IGU.Modelos.ModeloTablaDetalleVenta;
import BDGestion.BDGestionarDetalleVenta;
import Entidades.DetalleVenta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class JIF_ListadoVentas extends javax.swing.JInternalFrame {
 private static JIF_ListadoVentas instancia;
    ModeloTablaDetalleVenta tblv = new ModeloTablaDetalleVenta();
    private JIF_ListadoVentas() {
        initComponents();
        this.cargarTablaVenta();
    }
public static JIF_ListadoVentas getInstancia(){
        
        if( instancia == null || instancia.isClosed() ){
            instancia = new JIF_ListadoVentas();
        } 
        return instancia;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);

        tblVenta.setModel(this.tblv);
        jScrollPane1.setViewportView(tblVenta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVenta;
    // End of variables declaration//GEN-END:variables
 private void cargarTablaVenta() {
    try {
        BDGestionarDetalleVenta bd_gestProd = new BDGestionarDetalleVenta();
        ArrayList<DetalleVenta> arrPro = bd_gestProd.listar();

        System.out.println("Filas obtenidas de la BD: " + arrPro.size()); // 👈

        if (arrPro.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron datos.");
        }

        this.tblv.setListadoProducto(arrPro);
    } catch (Exception e) {
        e.printStackTrace(); // 👈 MUY IMPORTANTE
        JOptionPane.showMessageDialog(
            this,
            "ERROR: " + e.getMessage(),
            "Error de Base de Datos",
            JOptionPane.ERROR_MESSAGE);
    }
}
}
